%% ECES T580 Lab 6
% Bhautik (Brian) Amin

%% Lab 6.1.1

%% 
%Import data
[headers, seq] = fastaread('data.fasta');
%%
% Calculate Entropy and then Rseq. Calculate height for b x l table and
% then plot Rseq vs position (Assume e(n) = 0)

H = [];
R = [];
% find how many positions are in the sequence
temp = seq(1);
positions = length(temp{1}); % This assumes all sequences given are the same length
no_of_sequences = length(seq);
p_a = 0; p_t =0; p_g=0; p_c=0;

% Make a bxl table
height_table = eye(4,20);
for i=1:positions % For each position of the sequence
    p_a = 0; p_t =0; p_g=0; p_c=0;
    for j=1:no_of_sequences % For each sequence within the array of sequences
        temp = seq(j);
        seq_at_pos = upper(temp{1}(i)); % Pull out the char in the position
        switch seq_at_pos % Run through switch statement and increment found NT
            case 'A'
                p_a = p_a + 1;
            case 'G'
                p_g = p_g + 1;
            case 'T'
                p_t = p_t + 1;
            case 'C'
                p_c = p_c + 1;
        end

    end
    % Calculate the probability of each NT
    if (p_a == 0)
        p_a = 1;
    end
    if (p_g == 0)
         p_g = 1;
    end
    if (p_t == 0)
        p_t = 1;
    end
    if (p_c == 0)
        p_c =1;
    end
    
            
    p_a = p_a/positions;
    p_g = p_g/positions;
    p_c = p_c/positions;
    p_t = p_t/positions;
    % calculate H for this position
    H_pos = -p_a*log2(p_a) - p_t*log2(p_t) - p_g*log2(p_g) - p_c*log2(p_c);
    H = [H, H_pos];
    R = [R, 2-H_pos]; % Calculate Rseq for this position
    % Construct the height vs position table for this specfic position
    height_table(1,i) = p_a*(2-H_pos); % A
    height_table(2,i) = p_c*(2-H_pos); % C
    height_table(3,i) = p_g*(2-H_pos); % G
    height_table(4,i) = p_t*(2-H_pos); % T
    % Loop again for the next position
end

%%
% Now that we have our Rseq, positions, and B x L table we can plot:

%%
% Plot R vs Position using custom MATLAB code above
figure(1)
plot(1:positions, R)
title({'Rseq vs. position plot','Generated using custom MATLAB code'})
xlabel('Position')
ylabel('Bits')
%%
% Here is the Height vs Position table
height_table

%% Lab 6.2.1

%%
% Now we can try to plot using the built in MATLAB function seqlogo
[W, handle] = seqlogo(seq);

%%
% Show plot generated by Weblogo as well
figure(3)
imshow('web_logo.png')
title({'Rseq vs Position Plot', 'Generated by Web Logo'})

%%
% As we can see from all three plots, the general trend is the same.
% Where there are large features at positions 3,4,5, 13, 16, 17, 18 and so
% forth.
% These are consistent with all three plots. We can use a program such as
% paint to super impose the custom code generated plot and the web logo
% plot to see how they compare visually:
figure(4)
imshow('rough_comparison.jpg')
title('Rough Comparison using Paint')
%%
% Where in blue is the MATLAB generated plot and the black line is a hand
% traced (Not accurate) sketch over the web logo image. We can see that
% they both nearly line up



